# Generated by Django 4.0.5 on 2022-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
