# Generated by Django 4.0.5 on 2022-06-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_rate_average_remove_rate_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='app.post'),
        ),
    ]
