# Generated by Django 4.0.5 on 2022-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
